# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14b9e14a3db81bc2e80324212ed73a7ea9677eb521c77dd49b73bbc2bfd41341f7db154ed32ae9bdcf70ba86f01672f33f29cb228d71536958a3cc22f078af3

test:
  secret_key_base: 9011fb564c2a5f7e263949757a811116c6c7758eb3be2105b759275e36167292dff9f4901b35ad464eab894b54a992a9f8102e4d5e2d7c8f7a927987109e573b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
